CREATE TABLE ROL (
    COD_ROL INT AUTOINCREMENT,
    NOMBRE_ROL VARCHAR(255),
    CONSTRAINT PK_ROL PRIMARY KEY(COD_ROL)
);

CREATE TABLE USUARIOS (
    COD_USUARIO INT AUTOINCREMENT,
    NOMBRE_USUARIO VARCHAR(255),
    COD_ROL VARCHAR(255),
    CONTRASEÑA VARCHAR(255),
    RUT_USERNAME VARCHAR(255),
    CONSTRAINT PK_USUARIOS PRIMARY KEY(COD_USUARIO),
    CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (COD_ROL) REFERENCES ROL(COD_ROL)
);

CREATE TABLE CURSOS (
    COD_CURSO INT AUTOINCREMENT,
    NOMBRE_CURSO VARCHAR(255)
    CONSTRAINT PK_CURSOS PRIMARY KEY(COD_CURSO)
);

CREATE TABLE ALUMNOS (
    RUT_ALUMNO VARCHAR(255),
    COD_CURSO VARCHAR(255),
    NOMBRE_ALUMNO VARCHAR(255),
    SEGUNDO_NOMBRE_ALUMNO VARCHAR(255),
    APELLIDO_PATERNO_ALUMNO VARCHAR(255),
    APELLIDO_MATERNO_ALUMNO VARCHAR(255),
    ASISTENCIA VARCHAR(255),
    N_CELULAR_APODERADO VARCHAR(255)
    CONSTRAINT PK_USUARIOS PRIMARY KEY(COD_USUARIO),
    CONSTRAINT FK_COD_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSOS(COD_CURSOS)
);

----comentario
CREATE TABLE INASISTENCIA (
    COD_INASISTENCIA INT AUTOINCREMENT,
    RUT_ALUMNO VARCHAR(255),
    FECHA_INASISTENCIA VARCHAR(255),
    JUSTIFICATIVO VARCHAR(255)
    CONSTRAINT PK_INASISTENCIA PRIMARY KEY(COD_INASISTENCIA),
    CONSTRAINT FK_RUT_ALUMNO FOREIGN KEY (RUT_ALUMNO) REFERENCES ALUMNOS(RUT_ALUMNO)
);