CREATE TABLE ROL (
    COD_ROL INT AUTOINCREMENT,
    NOMBRE_ROL VARCHAR(255),
    CONSTRAINT PK_ROL PRIMARY KEY(COD_ROL)
);

CREATE TABLE USUARIOS (
    COD_USUARIO INT AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(255),
    COD_ROL INT, -- Modificado a INT para coincidir con el tipo de dato en la tabla ROL
    CONTRASEÑA VARCHAR(255),
    RUT_USERNAME VARCHAR(255),
    CONSTRAINT PK_USUARIOS PRIMARY KEY(COD_USUARIO),
    CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (COD_ROL) REFERENCES ROL(COD_ROL)
);


CREATE TABLE CURSOS (
    COD_CURSO INT AUTO_INCREMENT,
    NOMBRE_CURSO VARCHAR(255),
    CONSTRAINT PK_CURSOS PRIMARY KEY(COD_CURSO)
);


CREATE TABLE ALUMNOS (
    RUT_ALUMNO VARCHAR(255),
    COD_CURSO INT, -- Modificado a INT para coincidir con la tabla CURSOS
    NOMBRE_ALUMNO VARCHAR(255),
    SEGUNDO_NOMBRE_ALUMNO VARCHAR(255),
    APELLIDO_PATERNO_ALUMNO VARCHAR(255),
    APELLIDO_MATERNO_ALUMNO VARCHAR(255),
    ASISTENCIA VARCHAR(255),
    N_CELULAR_APODERADO VARCHAR(255),
    HUELLA_ALUMNO VARBINARY(255),
    CONSTRAINT PK_ALUMNOS PRIMARY KEY(RUT_ALUMNO), -- Cambiado PK de PK_USUARIOS a PK_ALUMNOS
    CONSTRAINT FK_COD_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSOS(COD_CURSO)
);


----comentario
CREATE TABLE ATRASOS (
    COD_ATRASOS INT AUTO_INCREMENT,
    RUT_ALUMNO VARCHAR(255),
    FECHA_ATRASOS DATE, -- Usar DATE en vez de VARCHAR para fechas
    JUSTIFICATIVO BOOLEAN, -- Cambiado a BOOLEAN para representar "sí" o "no"
    CONSTRAINT PK_ATRASOS PRIMARY KEY(COD_ATRASOS),
    CONSTRAINT FK_RUT_ALUMNO FOREIGN KEY (RUT_ALUMNO) REFERENCES ALUMNOS(RUT_ALUMNO)
);


CREATE TABLE NOTIFICACIONES (
    COD_NOTIFICACION INT AUTO_INCREMENT,
    RUT_ALUMNO VARCHAR(255),
    FECHA_NOTIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_NOTIFICACION VARCHAR(255), -- Atraso, Aviso General, etc.
    ESTADO_NOTIFICACION VARCHAR(255), -- Enviado, Pendiente, Error
    CONSTRAINT PK_NOTIFICACION PRIMARY KEY(COD_NOTIFICACION),
    CONSTRAINT FK_RUT_ALUMNO FOREIGN KEY (RUT_ALUMNO) REFERENCES ALUMNOS(RUT_ALUMNO)
);
