CREATE DATABASE plataforma_atrasos;

USE plataforma_atrasos;

CREATE TABLE ROL (
    COD_ROL INT AUTO_INCREMENT,
    NOMBRE_ROL VARCHAR(255),
    PRIMARY KEY(COD_ROL)
);

CREATE TABLE USUARIOS (
    COD_USUARIO INT AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(255),
    COD_ROL INT,
    CONTRASEÑA VARCHAR(255),
    RUT_USERNAME VARCHAR(255),
    PRIMARY KEY(COD_USUARIO),
    FOREIGN KEY (COD_ROL) REFERENCES ROL(COD_ROL)
);

CREATE TABLE CURSOS (
    COD_CURSO INT AUTO_INCREMENT,
    NOMBRE_CURSO VARCHAR(255),
    PRIMARY KEY(COD_CURSO)
);

CREATE TABLE ALUMNOS (
    RUT_ALUMNO VARCHAR(255),
    COD_CURSO INT,
    NOMBRE_ALUMNO VARCHAR(255),
    SEGUNDO_NOMBRE_ALUMNO VARCHAR(255),
    APELLIDO_PATERNO_ALUMNO VARCHAR(255),
    APELLIDO_MATERNO_ALUMNO VARCHAR(255),
    N_CELULAR_APODERADO VARCHAR(255),
    HUELLA_ALUMNO VARBINARY(255),
    JUSTIFICATIVO_RESIDENCIA TINYINT(1) DEFAULT 0,
    JUSTIFICATIVO_DEPORTIVO TINYINT(1) DEFAULT 0,
    JUSTIFICATIVO_MEDICO TINYINT(1) DEFAULT 0,
    PRIMARY KEY(RUT_ALUMNO),
    FOREIGN KEY (COD_CURSO) REFERENCES CURSOS(COD_CURSO)
);

CREATE TABLE ATRASOS (
    COD_ATRASOS INT AUTO_INCREMENT,
    RUT_ALUMNO VARCHAR(255),
    FECHA_ATRASOS DATE,
    JUSTIFICATIVO BOOLEAN,
    pdf_path VARCHAR(255),
    TIPO_JUSTIFICATIVO VARCHAR(255),
    PRIMARY KEY(COD_ATRASOS),
    FOREIGN KEY (RUT_ALUMNO) REFERENCES ALUMNOS(RUT_ALUMNO)
);
